apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: dnsmon
  name: dnsmon
spec:
  selector:
    app: dnsmon
  ports:
  - protocol: TCP
    port: 7999
    targetPort: 7999
